import type { StoneEstimatorOptions } from './types'

export const DEFAULT_STONE_ESTIMATOR_OPTIONS: StoneEstimatorOptions = {
  patchRadiusRatio: 4.2,
  ringInnerScale: 1.15,
  ringOuterScale: 1.95,
  localScale: 2.8,
  adaptiveBlockSize: 31,
  adaptiveOffset: 2,
  normalizedGain: 1.35,
  streamSelectZWeight: 1.2,
  streamSelectStdWeight: 0.12,

  stage1EmptyStdMax: 21,
  stage1EmptyContrastAbsMax: 12,
  stage1EmptyAbsZMax: 0.24,
  stage1BlackZMax: -0.56,
  stage1BlackContrastMin: 22,
  stage1BlackDarkRatioMin: 0.5,
  stage1BlackChromaMax: 12,
  stage1WhiteZMin: 0.2,
  stage1WhiteContrastMin: 14,
  stage1WhiteBrightRatioMin: 0.75,
  stage1WhiteDarkRatioMax: 0.26,
  stage1WhiteChromaMax: 9,

  stage2MadScale: 1.6,
  stage2MinSeedCount: 2,
  stage2MinMargin: 0.3,
  stage2UnknownToEmptyBias: 0.15,
  stage2ZWeight: 1.6,
  stage2ContrastWeight: 1.6,
  stage2RatioWeight: 1.1,
  stage2ChromaWeight: 0.6,
  stage2EmptyStdPenalty: 0.06,
  stage2EmptyContrastPenalty: 0.08,
  stage2EmptyZPenalty: 1.2,
  stage2FallbackBlackZMax: -0.22,
  stage2FallbackBlackContrastMin: 10,
  stage2FallbackBlackDarkRatioMin: 0.45,
  stage2FallbackWhiteZMin: 0.05,
  stage2FallbackWhiteContrastMin: 10,
  stage2FallbackWhiteBrightRatioMin: 0.7,
  stage2FallbackWhiteDarkRatioMax: 0.32,
  stage2FallbackWhiteChromaMax: 9,

  postConfidenceLock: 0.65,
  postIsolatedOppositeMin: 3,
  postDominantOppositeMin: 5,
  postMaxSameForFlip: 1,
}
